version: "3.7"
services:
 postgres:
     image: basha1994x/postgres
     environment:
       POSTGRES_USER: drkiq
       POSTGRES_PASSWORD: test_db_password
       PGDATA: /var/lib/postgresql/data/pgdata
     ports:
       - '5432:5432'
     volumes:
       - drkiq-postgres:/var/lib/postgresql/data
 redis:
     image: basha1994x/redis
     ports:
       - '6379:6379'
     volumes:
       - drkiq-redis:/var/lib/redis/data
 drkiq:
     environment:
      USER_ID: 1000
      GROUP_ID: 1000
      SECRET_TOKEN: Wa4Kdu6hMt3tYKm4jb9p4vZUuc7jBVFw
      WORKER_PROCESSES: 1
      LISTEN_ON: '0.0.0.0:8010'
      DATABASE_URL: 'postgresql://drkiq:test_db_password@postgres:5432/drkiq?encoding=utf8&pool=5&timeout=5000'
      CACHE_URL: 'redis://redis:6379/0'
      JOB_WORKER_URL: 'redis://redis:6379/0'
     image: basha1994x/drkiq_drkiq
     links:
       - postgres
       - redis
     ports:
       - '8010:8010'
 sidekiq:
     environment:
      USER_ID: '1000'
      GROUP_ID: '1000'
      SECRET_TOKEN: 'Wa4Kdu6hMt3tYKm4jb9p4vZUuc7jBVFw'
      WORKER_PROCESSES: '1'
      LISTEN_ON: '0.0.0.0:8010'
      DATABASE_URL: 'postgresql://drkiq:test_db_password@postgres:5432/drkiq?encoding=utf8&pool=5&timeout=5000'
      CACHE_URL: 'redis://redis:6379/0'
      RAILS_ENV: development
     image: basha1994x/drkiq_sidekiq
     links:
       - postgres
       - redis
 nginx:
     image: basha1994x/drkiq_nginx
     links:
       - drkiq
     ports:
       - '8020:8020'
volumes:
  drkiq-postgres:
  drkiq-redis:
